### ISSUE TITLE
Extend WASI Filesystem to support sqlite3

### ISSUE THREAD

**Issue by tracker1** [WebAssembly/wasi-filesystem#15]
Not sure if this the right place for this...  Wanted to just suggest that it would be really nice to support enough filesystem access to get sqlite3 working to where it can work on a database also being accessed by another application process.  I know it's somewhat odd to mention a specific library, but it seems that it's one of the most widely used libraries and focused around filesystem access, so being able to test it through webassembly/wasi and pass the sqlite test suite would be a massive win and prove the environment for most use cases of FS needs.

**Comment by sunfishcode** [comment]
One missing feature is `fcntl`+`F_SETLK`-style file locking. We didn't add file locking APIs to WASI initially because POSIX defines them to be associated with the *process*, not with the file descriptor, which is problematic for implementations that don't have a one-to-one relationship between instances and host processes. However, most OS's have alternative locking APIs that we could use here. If anyone's interested in investigating this, the first step here would be to do a survey of what file locking APIs exist on popular OS's, so we can design an API that would use them.

**Comment by sunfishcode** [comment]
Compiling sqlite with
 - `-DSQLITE_THREADSAFE=0` due to [threads](https://github.com/WebAssembly/WASI/issues/296)
 - `-DSQLITE_OMIT_LOAD_EXTENSION=1` due to `dlopen`
 - `-D_WASI_EMULATED_MMAN` to enable emulated mmap support

turns up the following features as being needed:
  - [File locking](#2)
  - `fchmod`, which can be supported once https://github.com/WebAssembly/WASI/pull/170 lands in a snapshot
 - `utimes` - a PR to implement this is now here: https://github.com/WebAssembly/wasi-libc/pull/242
 - `getpid` - a PR to implement this is now here: https://github.com/WebAssembly/wasi-libc/pull/243
 - `fchown`, `geteuid` are only used to detect when the process is running as root, and to change the database file owner to a non-root user. There's no pre-existing knob to disable these, but it's pretty easy to disable them.
 - `/dev/urandom` - WASI has `random_get`, so one option would be to add an emulation to libc `open` to special case the string "/dev/urandom" and implement it with `random_get` instead. Another is to disable random in sqlite using `-DSQLITE_OMIT_RANDOMNESS`.

**Comment by neimanpinchas** [comment]
Anyone can point to a polyfill how we could patch until its added?

**Comment by sunfishcode** [comment]
File locking (flock style) is now added to the API in https://github.com/WebAssembly/wasi-filesystem/pull/69.

**Comment by sunfishcode** [comment]
Threads, `dlopen` and `mmap` are outside the scope of wasi-filesystem, and file locking is now added, and all the other functions above have suitable answers, so we can now close this!
